version: '3.8'

services:
  api-server:
    image: 992382600796.dkr.ecr.us-east-1.amazonaws.com/dotlocker/api-server:${IMAGE_TAG}
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
