version: '3'

services:
  app:
    container_name: 'api_server'
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DEV_MODE: 'true'
    restart: always
    volumes:
      - .:/app/
      - /app/node_modules
    entrypoint: /bin/sh './scripts/run-node-dev.sh'
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - app_network

networks:
  app_network:
    external: true
